import type { TrackedStock } from "@/features/watchlist/watchlist.schemas";

export const defaultWatchlist: TrackedStock[] = [
  {
    $id: "ANANTRAJ",
    symbol: "ANANTRAJ",
    companyName: "Anant Raj Limited",
    exchanges: ["NSE"],
    aliases: ["Anant Raj"],
    isActive: true,
  },
  {
    $id: "BEL",
    symbol: "BEL",
    companyName: "Bharat Electronics Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "500049",
    aliases: ["Bharat Electronics"],
    isActive: true,
  },
  {
    $id: "BPCL",
    symbol: "BPCL",
    companyName: "Bharat Petroleum Corporation Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "500547",
    aliases: ["Bharat Petroleum"],
    isActive: true,
  },
  {
    $id: "HDFCBANK",
    symbol: "HDFCBANK",
    companyName: "HDFC Bank Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "500180",
    aliases: ["HDFC Bank"],
    isActive: true,
  },
  {
    $id: "INFY",
    symbol: "INFY",
    companyName: "Infosys Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "500209",
    aliases: ["Infosys"],
    isActive: true,
  },
  {
    $id: "ITC",
    symbol: "ITC",
    companyName: "ITC Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "500875",
    aliases: ["ITC"],
    isActive: true,
  },
  {
    $id: "NTPC",
    symbol: "NTPC",
    companyName: "NTPC Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "532555",
    aliases: ["NTPC"],
    isActive: true,
  },
  {
    $id: "SUZLON",
    symbol: "SUZLON",
    companyName: "Suzlon Energy Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "532667",
    aliases: ["Suzlon"],
    isActive: true,
  },
  {
    $id: "WIPRO",
    symbol: "WIPRO",
    companyName: "Wipro Limited",
    exchanges: ["NSE", "BSE"],
    bseCode: "507685",
    aliases: ["Wipro"],
    isActive: true,
  },
];
