import { BrokerConfig } from "./brokerage.schemas";

export const DEFAULT_BROKERS: BrokerConfig[] = [
	{
		id: "zerodha",
		name: "Zerodha",
		pricingUrl: "https://zerodha.com/pricing",
		dpChargeConfig: { brokerFee: 13.5, depositoryFee: 2.43, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0, maxFlat: 0 },
		equityIntraday: { percentage: 0.0003, maxFlat: 20 },
		futures: { percentage: 0.0003, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0003, maxFlat: 20 },
		currency: { percentage: 0.0003, maxFlat: 20 },
		mtf: { percentage: 0.0003, maxFlat: 20 }, // 18% p.a. calculated separately
	},
	{
		id: "groww",
		name: "Groww",
		pricingUrl: "https://groww.in/pricing",
		dpChargeConfig: { brokerFee: 13.5, depositoryFee: 2.43, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0.0005, maxFlat: 20 },
		equityIntraday: { percentage: 0.0005, maxFlat: 20 },
		futures: { percentage: 0.0005, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0005, maxFlat: 20 },
		currency: { percentage: 0.0005, maxFlat: 20 },
		mtf: { percentage: 0.0005, maxFlat: 20 },
	},
	{
		id: "angelone",
		name: "Angel One",
		pricingUrl: "https://www.angelone.in/pricing",
		dpChargeConfig: { brokerFee: 20, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0, maxFlat: 0 },
		equityIntraday: { percentage: 0.0003, maxFlat: 20 },
		futures: { percentage: 0.0003, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0003, maxFlat: 20 },
		currency: { percentage: 0.0003, maxFlat: 20 },
		mtf: { percentage: 0.0003, maxFlat: 20 },
	},
	{
		id: "upstox",
		name: "Upstox",
		pricingUrl: "https://upstox.com/pricing",
		dpChargeConfig: { brokerFee: 18.5, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0.0025, maxFlat: 20 },
		equityIntraday: { percentage: 0.0005, maxFlat: 20 },
		futures: { percentage: 0.0005, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0005, maxFlat: 20 },
		currency: { percentage: 0.0005, maxFlat: 20 },
		mtf: { percentage: 0.0025, maxFlat: 20 },
	},
	{
		id: "dhan",
		name: "Dhan",
		pricingUrl: "https://dhan.co/pricing",
		dpChargeConfig: { brokerFee: 12.5, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0, maxFlat: 0 },
		equityIntraday: { percentage: 0.0003, maxFlat: 20 },
		futures: { percentage: 0.0003, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0003, maxFlat: 20 },
		currency: { percentage: 0.0003, maxFlat: 20 },
		mtf: { percentage: 0.0003, maxFlat: 20 },
	},
	{
		id: "fyers",
		name: "FYERS",
		pricingUrl: "https://fyers.in/pricing",
		dpChargeConfig: { brokerFee: 12.5, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0, maxFlat: 0 },
		equityIntraday: { percentage: 0.0003, maxFlat: 20 },
		futures: { percentage: 0.0003, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.0003, maxFlat: 20 },
		currency: { percentage: 0.0003, maxFlat: 20 },
		mtf: { percentage: 0.0003, maxFlat: 20 },
	},
	{
		id: "5paisa",
		name: "5Paisa",
		pricingUrl: "https://www.5paisa.com/pricing",
		dpChargeConfig: { brokerFee: 12.5, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0, maxFlat: 20 },
		equityIntraday: { percentage: 0, maxFlat: 20 },
		futures: { percentage: 0, maxFlat: 20 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0, maxFlat: 20 },
		currency: { percentage: 0, maxFlat: 20 },
		mtf: { percentage: 0, maxFlat: 20 },
	},
	{
		id: "icicidirect",
		name: "ICICI Direct",
		pricingUrl: "https://www.icicidirect.com/pricing",
		dpChargeConfig: { brokerFee: 20, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0.0055, maxFlat: 0 },
		equityIntraday: { percentage: 0.000275, maxFlat: 0 },
		futures: { percentage: 0.000275, maxFlat: 0 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0.000275, maxFlat: 0 },
		currency: { percentage: 0.000275, maxFlat: 0 },
		mtf: { percentage: 0.0055, maxFlat: 0 },
	},
	{
		id: "hdfcsecurities",
		name: "HDFC Securities",
		pricingUrl: "https://www.hdfcsec.com/pricing",
		dpChargeConfig: { brokerFee: 20, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0.005, maxFlat: 0 },
		equityIntraday: { percentage: 0.0005, maxFlat: 0 },
		futures: { percentage: 0.0005, maxFlat: 0 },
		options: { percentage: 0, maxFlat: 100 }, // High flat fee for options usually
		commodity: { percentage: 0.0005, maxFlat: 0 },
		currency: { percentage: 0.0005, maxFlat: 0 },
		mtf: { percentage: 0.005, maxFlat: 0 },
	},
	{
		id: "kotaksecurities",
		name: "Kotak Securities",
		pricingUrl: "https://www.kotaksecurities.com/pricing",
		dpChargeConfig: { brokerFee: 20, depositoryFee: 0, isPerISIN: true, gstIncluded: false },
		equityDelivery: { percentage: 0.0025, maxFlat: 0 },
		equityIntraday: { percentage: 0, maxFlat: 0 }, // Trade Free plan
		futures: { percentage: 0, maxFlat: 0 },
		options: { percentage: 0, maxFlat: 20 },
		commodity: { percentage: 0, maxFlat: 0 },
		currency: { percentage: 0, maxFlat: 0 },
		mtf: { percentage: 0.0025, maxFlat: 0 },
	},
];
